---

- hosts: classrooms
  tasks:
   - name: Ensure Chromium policy directory exists
     become: true
     ansible.builtin.file:
       path: /etc/chromium/policies/managed
       state: directory
       mode: '0755'

   - name: Disable Chromium password saving
     become: true
     ansible.builtin.copy:
       content: |
         {
           "PasswordManagerEnabled": false
         }
       dest: /etc/chromium/policies/managed/disable_password_saving.json
       owner: root
       group: root
       mode: '0644'

   - name: Disable automatic sign-in
     become: true
     ansible.builtin.copy:
       content: |
         {
           "SigninAllowed": false,
           "SyncDisabled": true,
         }
       dest: /etc/chromium/policies/managed/disable_signin.json
       owner: root
       group: root
       mode: '0644'

